import type { SignComposition } from "./signCompose";

/**
 * Curated gloss → composition dictionary for common ISL signs.
 *
 * Each entry is cross-referenced against ISLRTC "Sign Learn" Android app
 * (primary) and indiansignlanguage.org (secondary). This is not a
 * linguistically exact implementation — for signs with complex trajectory
 * (e.g. classifier constructions, two-handed asymmetric movement) we
 * approximate with the closest primitives in our library.
 *
 * Not included in this dictionary (higher-priority path): the 14 signs
 * that have real ISLRTC mocap in public/signs/captures/. useTranscriptPipeline
 * checks mocap first, this dictionary second, fingerspelling third.
 */

export const SIGN_DECOMPOSITIONS: Record<string, SignComposition> = {
  // --- Pronouns & deixis --------------------------------------------------
  HE: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "SHOULDER_OPPOSITE",
    movement: "HOLD",
    durationMs: 900,
    source: "indiansignlanguage.org",
  },
  SHE: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "SHOULDER_OPPOSITE",
    movement: "HOLD",
    durationMs: 900,
    source: "indiansignlanguage.org",
  },
  WE: {
    handshape: "POINT_INDEX",
    palm: "PALM_IN",
    location: "CHEST",
    movement: "ARC_OUT",
    durationMs: 1100,
  },
  THEY: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "SIDE_EXTENDED",
    movement: "SIDE_TO_SIDE",
    durationMs: 1100,
  },
  YOUR: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 1000,
  },
  HIS: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "SHOULDER_OPPOSITE",
    movement: "HOLD",
    durationMs: 1000,
  },
  HER: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "SHOULDER_OPPOSITE",
    movement: "HOLD",
    durationMs: 1000,
  },

  // --- Greetings & politeness ---------------------------------------------
  GOODBYE: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "SPACE_HIGH",
    movement: "SIDE_TO_SIDE",
    durationMs: 1500,
  },
  SORRY: {
    handshape: "FIST",
    palm: "PALM_IN",
    location: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1400,
  },
  PLEASE: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1300,
  },
  NAMASTE: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "HOLD",
    durationMs: 1500,
    source: "cultural salutation",
  },

  // --- Verbs --------------------------------------------------------------
  GO: {
    handshape: "POINT_INDEX",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "FORWARD_SWEEP",
    durationMs: 1200,
  },
  COME: {
    handshape: "POINT_INDEX",
    palm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    movement: "ARC_FORWARD",
    durationMs: 1200,
  },
  EAT: {
    handshape: "BUNCHED",
    palm: "PALM_IN",
    location: "MOUTH",
    movement: "TAP_TWICE",
    durationMs: 1300,
    source: "indiansignlanguage.org",
  },
  DRINK: {
    handshape: "C",
    palm: "PALM_IN",
    location: "MOUTH",
    movement: "TAP_ONCE",
    durationMs: 1300,
    source: "indiansignlanguage.org",
  },
  READ: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "SIDE_TO_SIDE",
    durationMs: 1400,
  },
  WRITE: {
    handshape: "BABY_O",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "SIDE_TO_SIDE",
    durationMs: 1400,
  },
  WORK: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "TAP_TWICE",
    durationMs: 1400,
  },
  LEARN: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "ARC_UP",
    durationMs: 1400,
  },
  HELP: {
    handshape: "THUMB_UP",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_UP",
    location: "CHEST",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "ARC_UP",
    durationMs: 1400,
  },
  KNOW: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "FOREHEAD",
    movement: "TAP_ONCE",
    durationMs: 1200,
  },
  THINK: {
    handshape: "POINT_INDEX",
    palm: "PALM_IN",
    location: "TEMPLE",
    movement: "TAP_ONCE",
    durationMs: 1200,
  },
  SPEAK: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "MOUTH",
    movement: "ARC_OUT",
    durationMs: 1300,
  },
  LISTEN: {
    handshape: "C",
    palm: "PALM_OUT",
    location: "EAR",
    movement: "HOLD",
    durationMs: 1200,
  },
  NEED: {
    handshape: "HOOK_INDEX",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "TAP_TWICE",
    durationMs: 1200,
  },
  HAVE: {
    handshape: "BENT_5",
    nondominantHandshape: "BENT_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "HOLD",
    durationMs: 1100,
  },
  LOVE: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "HOLD",
    durationMs: 1400,
  },

  // --- Nouns --------------------------------------------------------------
  HOME: {
    handshape: "BUNCHED",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "TAP_ONCE",
    durationMs: 1200,
    source: "indiansignlanguage.org",
  },
  SCHOOL: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "CLAP_TWICE",
    durationMs: 1400,
    source: "indiansignlanguage.org",
  },
  FOOD: {
    handshape: "BUNCHED",
    palm: "PALM_IN",
    location: "MOUTH",
    movement: "TAP_ONCE",
    durationMs: 1200,
  },
  BOOK: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_UP",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "HOLD",
    durationMs: 1300,
  },
  FATHER: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "TEMPLE",
    movement: "TAP_TWICE",
    durationMs: 1300,
  },
  MOTHER: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "CHIN",
    movement: "TAP_TWICE",
    durationMs: 1300,
  },
  DOCTOR: {
    handshape: "V",
    palm: "PALM_IN",
    location: "NEUTRAL_FORWARD",
    movement: "TAP_ONCE",
    durationMs: 1300,
  },
  TEACHER: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "TEMPLE",
    movement: "ARC_FORWARD",
    durationMs: 1400,
  },
  STUDENT: {
    handshape: "C",
    palm: "PALM_IN",
    location: "FOREHEAD",
    movement: "ARC_UP",
    durationMs: 1300,
  },

  // --- WH / grammar -------------------------------------------------------
  WHO: {
    handshape: "POINT_INDEX",
    palm: "PALM_IN",
    location: "CHIN",
    movement: "CIRCLE_CW",
    durationMs: 1200,
  },
  WHERE: {
    handshape: "POINT_INDEX",
    palm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    movement: "SIDE_TO_SIDE",
    durationMs: 1200,
  },
  WHEN: {
    handshape: "POINT_INDEX",
    nondominantHandshape: "POINT_INDEX",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "CIRCLE_CW",
    durationMs: 1300,
  },
  WHY: {
    handshape: "V",
    palm: "PALM_IN",
    location: "FOREHEAD",
    movement: "TAP_TWICE",
    durationMs: 1300,
  },
  HOW: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_UP",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "SIDE_TO_SIDE",
    durationMs: 1300,
  },
  NOT: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "CHIN",
    movement: "BRUSH_ACROSS",
    durationMs: 1200,
  },

  // --- Time ---------------------------------------------------------------
  TODAY: {
    handshape: "POINT_INDEX",
    palm: "PALM_DOWN",
    location: "NEUTRAL_LOW",
    movement: "TAP_TWICE",
    durationMs: 1100,
  },
  YESTERDAY: {
    handshape: "THUMB_UP",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "ARC_OUT",
    durationMs: 1200,
  },
  TOMORROW: {
    handshape: "THUMB_UP",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "ARC_FORWARD",
    durationMs: 1200,
  },
  NOW: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_UP",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "TAP_ONCE",
    durationMs: 900,
  },
  MORNING: {
    handshape: "FLAT_5",
    palm: "PALM_UP",
    location: "NEUTRAL_LOW",
    movement: "ARC_UP",
    durationMs: 1300,
  },
  NIGHT: {
    handshape: "FLAT_5",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "DOWNWARD_THROW",
    durationMs: 1300,
  },

  // --- Adjectives / state -------------------------------------------------
  GOOD: {
    handshape: "THUMB_UP",
    palm: "PALM_IN",
    location: "NEUTRAL_FORWARD",
    movement: "ARC_FORWARD",
    durationMs: 1200,
  },
  BAD: {
    handshape: "Y",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "DOWNWARD_THROW",
    durationMs: 1200,
  },
  HAPPY: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1400,
  },
  SAD: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "DOWNWARD_THROW",
    durationMs: 1400,
  },
  HUNGRY: {
    handshape: "C",
    palm: "PALM_IN",
    location: "CHEST",
    movement: "DOWNWARD_THROW",
    durationMs: 1200,
  },
  TIRED: {
    handshape: "BENT_5",
    palm: "PALM_IN",
    location: "CHEST",
    movement: "DOWNWARD_THROW",
    durationMs: 1300,
  },

  // --- Numbers (ISL counting — thumb-up, index-up, etc.) -----------------
  ONE: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 800,
  },
  TWO: {
    handshape: "V",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 800,
  },
  THREE: {
    handshape: "THREE",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 800,
  },
  FOUR: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 800,
  },
  FIVE: {
    handshape: "SPREAD_5",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 800,
  },

  // --- Deaf-cultural hook signs ------------------------------------------
  ASTRONAUT: {
    handshape: "C",
    nondominantHandshape: "C",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "FOREHEAD",
    nondominantLocation: "FOREHEAD",
    movement: "HOLD",
    durationMs: 1500,
    source: "approximation: helmet classifier",
  },
  EARTH: {
    handshape: "THUMB_UP",
    nondominantHandshape: "FIST",
    palm: "PALM_IN",
    nondominantPalm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "CIRCLE_CW",
    durationMs: 1400,
  },
  STAR: {
    handshape: "POINT_INDEX",
    nondominantHandshape: "POINT_INDEX",
    palm: "PALM_OUT",
    nondominantPalm: "PALM_OUT",
    location: "SPACE_HIGH",
    nondominantLocation: "SPACE_HIGH",
    movement: "TAP_TWICE",
    durationMs: 1200,
  },
  SPACE: {
    handshape: "FLAT_5",
    palm: "PALM_UP",
    location: "SPACE_HIGH",
    movement: "ARC_OUT",
    durationMs: 1400,
  },

  // --- Extended verbs -----------------------------------------------------
  SIT: {
    handshape: "V",
    nondominantHandshape: "BUNCHED",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "TAP_ONCE",
    durationMs: 1200,
    source: "indiansignlanguage.org",
  },
  STAND: {
    handshape: "V",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "HOLD",
    durationMs: 1200,
    source: "indiansignlanguage.org",
  },
  SLEEP: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "HOLD",
    durationMs: 1300,
    source: "indiansignlanguage.org",
  },
  TALK: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "MOUTH",
    movement: "ARC_FORWARD",
    durationMs: 1300,
  },
  ASK: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "CHIN",
    movement: "ARC_FORWARD",
    durationMs: 1200,
  },
  TELL: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "MOUTH",
    movement: "FORWARD_SWEEP",
    durationMs: 1200,
  },
  UNDERSTAND: {
    handshape: "POINT_INDEX",
    palm: "PALM_IN",
    location: "TEMPLE",
    movement: "TAP_TWICE",
    durationMs: 1200,
    source: "indiansignlanguage.org",
  },
  REMEMBER: {
    handshape: "THUMB_UP",
    palm: "PALM_IN",
    location: "TEMPLE",
    movement: "HOLD",
    durationMs: 1200,
  },
  FORGET: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "FOREHEAD",
    movement: "BRUSH_ACROSS",
    durationMs: 1300,
  },
  WAIT: {
    handshape: "FLAT_5",
    palm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    movement: "WIGGLE_FINGERS",
    durationMs: 1500,
  },
  STOP: {
    handshape: "FLAT_5",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "HOLD",
    durationMs: 1000,
  },
  MEET: {
    handshape: "POINT_INDEX",
    nondominantHandshape: "POINT_INDEX",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "CLAP_TWICE",
    durationMs: 1200,
  },
  GIVE: {
    handshape: "FLAT_5",
    palm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    movement: "ARC_FORWARD",
    durationMs: 1300,
  },
  TAKE: {
    handshape: "FIST",
    palm: "PALM_IN",
    location: "NEUTRAL_FORWARD",
    movement: "ARC_UP",
    durationMs: 1200,
  },
  OPEN: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "ARC_OUT",
    durationMs: 1300,
  },
  CLOSE: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "SHOULDER_SAME",
    nondominantLocation: "SHOULDER_OPPOSITE",
    movement: "CLAP_TWICE",
    durationMs: 1200,
  },
  PLAY: {
    handshape: "Y",
    nondominantHandshape: "Y",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "WIGGLE_FINGERS",
    durationMs: 1400,
  },
  HEAR: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "EAR",
    movement: "TAP_TWICE",
    durationMs: 1100,
  },

  // --- Extended nouns -----------------------------------------------------
  HOUSE: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_SIDE_IN",
    nondominantPalm: "PALM_SIDE_OUT",
    location: "FOREHEAD",
    nondominantLocation: "FOREHEAD",
    movement: "ARC_OUT",
    durationMs: 1400,
    source: "classifier: roof shape",
  },
  CAR: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1300,
    source: "classifier: steering wheel",
  },
  PHONE: {
    handshape: "Y",
    palm: "PALM_IN",
    location: "EAR",
    movement: "HOLD",
    durationMs: 1000,
  },
  MONEY: {
    handshape: "BABY_O",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "TAP_TWICE",
    durationMs: 1200,
  },
  FAMILY: {
    handshape: "F",
    nondominantHandshape: "F",
    palm: "PALM_OUT",
    nondominantPalm: "PALM_OUT",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1400,
  },
  BROTHER: {
    handshape: "THUMB_UP",
    palm: "PALM_IN",
    location: "FOREHEAD",
    movement: "TAP_ONCE",
    durationMs: 1300,
  },
  SISTER: {
    handshape: "Y",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "TAP_ONCE",
    durationMs: 1300,
  },
  CHILD: {
    handshape: "FLAT_5",
    palm: "PALM_DOWN",
    location: "NEUTRAL_LOW",
    movement: "TAP_TWICE",
    durationMs: 1200,
  },
  PERSON: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "DOWNWARD_THROW",
    durationMs: 1200,
  },
  PLACE: {
    handshape: "FLAT_5",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "CIRCLE_CW",
    durationMs: 1200,
  },

  // --- Extended adjectives ------------------------------------------------
  BIG: {
    handshape: "C",
    nondominantHandshape: "C",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "ARC_OUT",
    durationMs: 1200,
  },
  SMALL: {
    handshape: "BABY_O",
    nondominantHandshape: "BABY_O",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "CLAP_TWICE",
    durationMs: 1100,
  },
  OLD: {
    handshape: "FIST",
    palm: "PALM_IN",
    location: "CHIN",
    movement: "DOWNWARD_THROW",
    durationMs: 1300,
  },
  NEW: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_UP",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_LOW",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "BRUSH_ACROSS",
    durationMs: 1200,
  },
  HOT: {
    handshape: "C",
    palm: "PALM_IN",
    location: "MOUTH",
    movement: "ARC_OUT",
    durationMs: 1200,
  },
  COLD: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "SIDE_TO_SIDE",
    durationMs: 1300,
  },
  BEAUTIFUL: {
    handshape: "FLAT_5",
    palm: "PALM_IN",
    location: "CHEEK",
    movement: "CIRCLE_CW",
    durationMs: 1400,
  },
  FAST: {
    handshape: "POINT_INDEX",
    palm: "PALM_SIDE_IN",
    location: "NEUTRAL_FORWARD",
    movement: "BRUSH_ACROSS",
    durationMs: 900,
  },
  SLOW: {
    handshape: "FLAT_5",
    palm: "PALM_DOWN",
    location: "NEUTRAL_LOW",
    movement: "ARC_UP",
    durationMs: 1800,
  },
  THIRSTY: {
    handshape: "POINT_INDEX",
    palm: "PALM_IN",
    location: "MOUTH",
    movement: "DOWNWARD_THROW",
    durationMs: 1300,
  },

  // --- Emotions / states (extended) --------------------------------------
  ANGRY: {
    handshape: "CLAW",
    palm: "PALM_IN",
    location: "FOREHEAD",
    movement: "HOLD",
    durationMs: 1300,
  },
  SCARED: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "TAP_TWICE",
    durationMs: 1200,
  },
  EXCITED: {
    handshape: "W",
    nondominantHandshape: "W",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1300,
  },
  SURPRISED: {
    handshape: "SPREAD_5",
    nondominantHandshape: "SPREAD_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_IN",
    location: "FOREHEAD",
    nondominantLocation: "FOREHEAD",
    movement: "ARC_OUT",
    durationMs: 1200,
  },

  // --- Extended time/quantity --------------------------------------------
  DAY: {
    handshape: "POINT_INDEX",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_IN",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_LOW",
    movement: "ARC_OUT",
    durationMs: 1300,
  },
  YEAR: {
    handshape: "POINT_INDEX",
    nondominantHandshape: "FIST",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "CHEST",
    nondominantLocation: "CHEST",
    movement: "CIRCLE_CW",
    durationMs: 1300,
  },
  AFTERNOON: {
    handshape: "FLAT_5",
    nondominantHandshape: "FLAT_5",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "SHOULDER_OPPOSITE",
    nondominantLocation: "CHEST",
    movement: "HOLD",
    durationMs: 1300,
  },
  MANY: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_UP",
    nondominantPalm: "PALM_UP",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "ARC_OUT",
    durationMs: 1200,
  },
  ALL: {
    handshape: "FLAT_5",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "CIRCLE_CW",
    durationMs: 1300,
  },

  // --- Modals / auxiliaries (important for natural sentences) ------------
  CAN: {
    handshape: "FIST",
    nondominantHandshape: "FIST",
    palm: "PALM_DOWN",
    nondominantPalm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    nondominantLocation: "NEUTRAL_FORWARD",
    movement: "TAP_ONCE",
    durationMs: 1100,
  },
  MUST: {
    handshape: "POINT_INDEX",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "DOWNWARD_THROW",
    durationMs: 1200,
  },

  // --- Extended pronouns --------------------------------------------------
  HERE: {
    handshape: "POINT_INDEX",
    palm: "PALM_DOWN",
    location: "NEUTRAL_LOW",
    movement: "TAP_TWICE",
    durationMs: 1000,
  },
  THERE: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "NEUTRAL_FORWARD",
    movement: "ARC_FORWARD",
    durationMs: 1100,
  },
  THIS: {
    handshape: "POINT_INDEX",
    palm: "PALM_DOWN",
    location: "NEUTRAL_FORWARD",
    movement: "TAP_ONCE",
    durationMs: 900,
  },
  THAT: {
    handshape: "POINT_INDEX",
    palm: "PALM_OUT",
    location: "SHOULDER_OPPOSITE",
    movement: "ARC_FORWARD",
    durationMs: 1000,
  },
};

/** Case-insensitive lookup — glosses arrive uppercase. */
export function decompositionFor(gloss: string): SignComposition | null {
  return SIGN_DECOMPOSITIONS[gloss.toUpperCase()] ?? null;
}

export type DecomposedGloss = keyof typeof SIGN_DECOMPOSITIONS;
